spring:
  application:
    name: eureka-server
  datasource:
    username: vlad
    url: jdbc:postgresql://localhost:5432/shop
    password: vlad

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false


